Legacy/bonej/pom.xml, Legacy/pom.xml, Legacy/pqct/pom.xml, Legacy/util/pom.xml
These changes move more control of Maven properties to the parent pom.xml.
To summarize:
* Remove relative pom path and add module properties so modules can be treated more independently
* Inherit from pom-fiji so most of the version specifications can be removed
* Remove inherited repository blocks from modules
This also sets the versions of all components to SNAPSHOTs.
=> Maven improvements

pom.xml
It is not the parent for anything in the build, but rather only a convenience to build everything at once. As such, let's not deploy it.
Hopefully, this fixes the Travis build.
=> Do not deploy the aggregator POM

Modern/ops/src/main/java/org/bonej/ops/BoxIntersect.java, Modern/ops/src/main/java/org/bonej/ops/mil/LineGrid.java, Modern/ops/src/test/java/org/bonej/ops/BoxIntersectTest.java, Modern/ops/src/test/java/org/bonej/ops/mil/LineGridTest.java, Modern/ops/src/test/java/org/bonej/ops/mil/MILPOCSampling.java, Modern/ops/src/test/java/org/bonej/ops/mil/MeanInterceptLengthProofOfConcept.java
Adds a proof of concept manual test class that shows that the grid of vectors described by the `LineGrid` class can be used to randomly sample an image without bias.
The PoC revealed a bias in the earlier design of `LineGrid`, which led to major refactoring also in this PR.
=> Mean intercept length proof of concept

Modern/ops/src/main/java/org/bonej/ops/mil/LineGrid.java, Modern/ops/src/main/java/org/bonej/ops/mil/MILGrid.java, Modern/ops/src/test/java/org/bonej/ops/mil/LineGridTest.java, Modern/ops/src/test/java/org/bonej/ops/mil/MILGridTest.java, Modern/ops/src/test/java/org/bonej/ops/mil/MILPOCDirectionComponents.java, Modern/ops/src/test/java/org/bonej/ops/mil/MILPOCSampling.java
Adds an Op that samples the mean intercept length of an interval. It's used to analyse the anisotropy of an image.
=> Mean Intercept Lengths op

IntegrationTestLogs/Anisotropy.txt, Modern/ops/src/main/java/org/bonej/ops/mil/LineGrid.java, Modern/ops/src/main/java/org/bonej/ops/mil/MILGrid.java, Modern/ops/src/test/java/org/bonej/ops/mil/LineGridTest.java, Modern/ops/src/test/java/org/bonej/ops/mil/MILGridTest.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java
When coding this branch, I realised that the `MILGrid` op and ellipsoid fitting didn't fit together. They didn't produce stable results within small tolerance, and input parameter values affected the result too much. This pull request creates a prototype Anisotropy command, that uses a modified MILGrid op. 
The modified MILGrid returns the three shortest MIL vectors it sampled on the image. In the command the op is repeated n times and then it tries to fit an ellipsoid on the point cloud that results from these calls. The results change less from run to run than in BoneJ1, and seem intuitive: a cube is very isotropic, a stack of "sheets" parallel to the xy-plane is anisotropic, and "Bat cochlea volume" is somewhere in between.
* Refactors the `LineGrid` class
* Refactors the `MILGrid` …
=> Anisotropy wrapper

Modern/ops/src/main/java/org/bonej/ops/ellipsoid/DistanceFromEllipsoidSurfaceOp.java, Modern/ops/src/test/java/org/bonej/ops/ellipsoid/DistanceFromEllipsoidSurfaceOpTest.java
A simple op that numerically calculates the
shortest distance from a point to the ellipsoid
surface, provided there is a unique solution.
This may come in handy for quantifying the 
error of the ellipsoid fitting in the Anisotropy
wrapper as well as any ellipsoid-fitting at local
trabecular bone scales (EF, tensor scale,etc).
=> DistanceFromEllipsoidSurfaceOp

Legacy/bonej/src/main/resources/plugins.config
Legacy and IJ2 plugins are separated by a line. Whether a plugin is
legacy or not should be relatively invisible to end users.
=> Put all the BoneJ plugins in the same menu

Legacy/util/src/main/java/org/bonej/util/ResultInserter.java
Result inserter works more intuitively if a bunch of new results are added to the last line rather than the first line a duplicate entry is found.
=> Fix result inserter logic (Legacy)

Modern/utilities/src/main/java/org/bonej/utilities/SharedTable.java, Modern/utilities/src/test/java/org/bonej/utilities/SharedTableTest.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FitEllipsoidWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IsosurfaceWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FractalDimensionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceAreaWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThicknessWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/tableTools/SharedTableCleanerTest.java
This PR addresses:
#125 Storing result table values as Double rather than String
Using the rowHeader special column rather than a 'Label' column to store image titles
#117 Filling the table from the bottom when duplicate image titles are present in the rowHeaders
#124 No more alphabetical sorting
=> Updates to SharedTable

IntegrationTestLogs/SharedTable.txt, IntegrationTestLogs/SharedTableCleaner.txt, Modern/utilities/src/main/java/org/bonej/utilities/SharedTable.java, Modern/utilities/src/test/java/org/bonej/utilities/SharedTableTest.java
* Fixes issue #123 
* Fixes a potential bug in `SharedTable` when comparing cell values
* Does code maintenance in `SharedTable` and its tests
* Updates unit and manual tests
This is a bit of a quick-fix, since in any case `imagej.table` is soon going to change to `scijava.table`. If the weirdness in clearing the copy in `SharedTable.getTable` still persists after those changes, they should be addressed at that time.
However I argue it's better to return a copy in this way than to expose the `Table` through the public API. Returning a reference to the instance would allow altering the contents of the `Table` against the way we want `SharedTable` to be used.
Maybe the best way to solve this problem would be to add a read-only interfaces for the tables in `scijava.table` a la `Vector3dc` …
=> Return a copy of SharedTable

Modern/utilities/src/main/java/org/bonej/utilities/ElementUtil.java, Modern/utilities/src/test/java/org/bonej/utilities/ElementUtilTest.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java
Remove high level things from inner loop like Object creation and
HashSet.add(), replacing them with low-level comparison logic.
If needed the same could be done using Object.equals() or similar, to
make isBinary() more generic.
Partially addresses #108 (see also https://github.com/imagej/imagej-ops/commit/dd5a3e3015e9f72e936447ba95c0cac84e822a4d#commitcomment-33284909)
=> Speed up isBinary() check

Legacy/bonej/src/main/java/org/bonej/plugins/Connectivity.java, Legacy/bonej/src/main/resources/plugins.config, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java
Legacy Connectivity is about twice as fast but
does not have the advantage of ImgLib2's data
structures. Modern connectivity is half speed
but is more flexible in its accessibility from
client code and different data sources (network, disk,
memory, etc.)
Fixes #108
See also https://github.com/imagej/imagej-ops/pull/605
=> Give users the choice of legacy/modern Connectivity

pom.xml
Travis build still fails after merging #177 - @imagejan on gitter thinks updating scijava parent to `26.0.0` should fix this - so let's try. I would be interested in what happens underneath if anyone can explain it? Why is Travis on Github happy with the changes, but Travis itself not? Thanks for all your help
=> update scijava parent in pom

Modern/ops/src/main/java/org/bonej/ops/mil/MILPlane.java, Modern/ops/src/test/java/org/bonej/ops/mil/MILPlaneTest.java, Modern/utilities/pom.xml, Modern/utilities/src/main/java/org/bonej/utilities/Visualiser.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java
Adresses #182 
This commit introduces a new utility for visualising data,
which users may find helpful to understand their anisotropy results.
The default sampling increment is set to 2.3 × pixel spacing,
which is about where the pixel spacing no longer creates an
'imprint' on the MIL of the structure's texture.
If sampling increment is too small (≲ 2px), the pixel grid size starts
to interfere with the feature size.
Count every foreground/background boundary
following the definition in Odgaard 1997, and the use in BoneJ1
Print the eigenvalues to the results table, after a user request
=> Enhance Anisotropy to give consistent results

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java
This test was implicitly selecting the option to show the MIL points in the 3D viewer, but then failing because it couldn't find a native library presumably to use to run the test.
=> Don't attempt to draw points in the 3D viewer during testing

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Not masking leads to bias in the measurements, so it is unsafe to allow
masking to be disabled permanently.
=> Make pixel mask option not persist. Resets to true on each run.

Modern/ops/src/main/java/org/bonej/ops/mil/ParallelLineGenerator.java, Modern/ops/src/main/java/org/bonej/ops/mil/ParallelLineMIL.java, Modern/ops/src/main/java/org/bonej/ops/mil/PlaneParallelLineGenerator.java, Modern/ops/src/test/java/org/bonej/ops/mil/ParallelLineMILTest.java, Modern/ops/src/test/java/org/bonej/ops/mil/PlaneParallelLineGeneratorTest.java, Modern/utilities/pom.xml, Modern/utilities/src/main/java/org/bonej/utilities/Visualiser.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java, pom.xml
@mdoube I had an idea how to improve Anisotropy, and wanted to open this PR for discussion, before it's ready.
The current version blindly shoots sampling vectors from a plane through through the image. This plane needs to be bigger than the stack, so that the vectors have the chance to cover the entire stack, regardless of the plane's orientation. It needs to be _d x d_ to be exact, where _d_ is the largest diagonal of the stack. This means that some of the random vectors are going to miss the stack entirely. The result is that the total length of the MIL vector sampled through the stack will change between runs. I think this is why you see variance in the anisotropy of an empty stack, and why it's not _0.0_.
Here I simply keep generating new random vectors, until a predetermined MIL …
=> Refactor Anisotropy

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AbstractWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/CommonWrapperTests.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FitEllipsoidWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FractalDimensionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SkeletoniseWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceAreaWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThicknessWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/tableTools/SharedTableCleanerTest.java
Calculates minimum increment for Anisotropy dynamically based on pixel size, as suggested in PR #197. For now it's just `sqrt(3)` because the plugin doesn't yet handle calibration, but the necessary callbacks are now there for the future.
Also fixes problems in wrapper tests that I noticed when adding new tests for minimum increment. Basically mocking was handled sloppily, mock behaviour wasn't properly reset between tests etc.
=> Add minimum increment to Anisotropy based on pixel size

Legacy/bonej/src/main/java/org/bonej/DebugLauncher.java, Legacy/bonej/src/main/java/org/bonej/plugins/Orienteer.java, Legacy/bonej/src/main/java/org/bonej/plugins/SliceGeometry.java
This PR fixes issue #195.
In addition it
* Makes the constructor `Orienteer()` `public` again so that the plugin can be run.
* Makes sure that `Orienteer` only calls `UsageReporter` when it's launched as a plugin (and calls it once per run)
@mdoube Since you understand these plugins much better, would you mind checking that they work correctly?
=> Fix issue #195

Modern/wrapperPlugins/pom.xml, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FitEllipsoidWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SkeletoniseWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/Common.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/UsageReporterOptions.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/CommonTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtilsTest.java, Modern/wrapperPlugins/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
* Adds a workaround for #207 
* Adds a utility method which allows plugins to cancel without showing a message dialog, when a macro is running
=> Macro fixes

pom.xml
- as recommended in issue #193
Advice is to put Maven version properties in the top-level POM.
=> Include a specific version for LocalThickness_ (4.0.3)

Legacy/bonej/src/main/java/org/bonej/plugins/SliceGeometry.java
This feature provides calculation of density-weighted centroid and
second moments of area (and by extension polar moment of inertia and
section modulus). It assumes a linear relationship between pixel value
and physical density between minimum and maximum values, and 0 and 100%
'solid' outside those values.
This feature was developed for and first used in:
Doube M, Felder AA, Chua MY, Lodhia K, Kłosowski MM, Hutchinson JR,
Shefelbine SJ. 2018 Limb bone scaling in hopping macropods and
quadrupedal artiodactyls. Roy. Soc. Open Sci. 5, 180152.
(doi:[10.1098/rsos.180152](https://doi.org/10.1098/rsos.180152))
=> Add partial volume compensation to Slice Geometry

Legacy/bonej/src/main/java/org/bonej/plugins/Moments.java
This commit adds an option to display the 3 × 3 eigenvector matrix as 9 items in the Result table, listed as `v[X|Y|Z][0-2]`. Items are listed column first.
Code is similar to that in [`ParticleCounter`](https://github.com/bonej-org/BoneJ2/blob/dd7babcfa9193d5902f2ab7b3b5c469c73eeca65/Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java#L294)  for consistency.
This feature was requested [on the forum](https://forum.image.sc/t/eigenvector-precision-for-moments-of-inertia/36138).
=> Moments of inertia: add option for detailed eigenvector output in the Result table

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/BoneJCommand.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FitEllipsoidWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SkeletoniseWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AbstractWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FitEllipsoidWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FractalDimensionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SkeletoniseWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceAreaWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThicknessWrapperTest.java
* Creates an abstract base class `BoneJCommand` that all wrapper plugins extend
* Moves shared functionality to the base class
As a side note I tried moving the common output 
```
@Parameter(type = ItemIO.OUTPUT, label = "BoneJ results")
private Table<DefaultColumn<Double>, Double> resultsTable;
```
but that doesn't seem to be possible (tests started to throw `NullPointerException`).
I checked that `mvn test -PallTests` passes, and manually ran all the modern plugins.
=> Move repeated code to an abstract base class

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/BoneJCommand.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FitEllipsoidWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java
Contrary to what I claimed in #245 it's possible to move the results table to the base class. The failing tests mentioned failed because one of our commands didn't call its results table `resultsTable`.
=> Move results table to BoneJCommand

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java, Legacy/bonej/src/test/java/org/bonej/plugins/ConnectedComponentsTest.java
This PR fixes #261, which resulted from an implicit creation of the background particle ID (0) that was either not created, or created and then destroyed when there was no foreground particle in the zeroth image processing chunk.
=> Explicity create and protect the background particle identity

Legacy/bonej/LICENSE.txt, Legacy/util/LICENSE.txt, Modern/ops/LICENSE.txt, Modern/utilities/LICENSE.txt, Modern/wrapperPlugins/LICENSE.txt
The release script automatically generated `LICENSE.txt` files, one for each module `JAR`.
=> Add LICENSE.txt to each module

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java, Legacy/bonej/src/main/java/org/bonej/plugins/SliceGeometry.java, Modern/ops/src/main/java/org/bonej/ops/ellipsoid/EllipsoidFactorOutputGenerator.java, Modern/ops/src/main/java/org/bonej/ops/ellipsoid/EllipsoidOptimisationStrategy.java, Modern/ops/src/main/java/org/bonej/ops/ellipsoid/OptimisationParameters.java, Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidFactorOutputGeneratorTest.java, Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidOptimisationStrategyTest.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtils.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtilsTest.java
This PR addresses issues with EF being a bit too verbose for most users, fixes a rarely-encountered bug in Particle Analyser, and restores Imax and Imin nomenclature to the previous in Slice Geometry (min & max refer now to the principal axes around which the moments are calculated, which has the effect that Imin > Imax in most cases).
=> Improvements to EF user experience, bug fixes to Particle Analyser & Slice Geometry

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java
Addresses issue #276
Particle labels were previously capped at 2<sup>23</sup> which is the limit of integer precision represented by `float`. This limit was exceeded by large images (e.g. 150 GB) with many particles (3 million) running on computers with many threads (e.g. 132).
This solution allows the entire range of positive `int` (up to 2<sup>32</sup>) to be used during particle labelling and analysis of the resulting label array. The limitation of **displaying** labels in ImageJ1 as 32-bit `float` images remains.
=> Expand the allowable label space to use all positive int values

Legacy/bonej/src/main/java/org/bonej/plugins/Connectivity.java
This is a small performance enhancement that reduces by half the number of times pixels have to be looked up from the image stack. Also some dead code is removed. Same was suggested [here](https://github.com/maarzt/imagej-ops/commit/5e1ef886b3f84ea278c5710c0d89638f9fcaaba8#diff-a06b9f93651e2b6be331719c7f00d7af4a3460fc8dff3987dcc5edfa9b20c9fd) for Modern Connectivity, but so far I haven't been able to get that to compile & pass tests.
Array lookups for the octant table are removed in favour of 8 primitive `byte`.
=> Reduce pixel and array lookups to get a c. 35% reduction in execution time

Legacy/bonej/src/main/java/org/bonej/plugins/UsageReporter.java, pom.xml
Usage data were not being collected for Legacy plugins when debug mode was off.
=> Usage debug

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java
This approach to setting chunk sizes no longer throws an AIOOB, but does
mean that the last chunk can be larger than the rest on big stacks.
Fixes #286
=> Fix an AIOOB exception due to bad setting of chunk sizes

Legacy/bonej/src/main/java/org/bonej/plugins/Purify.java, Legacy/bonej/src/test/java/org/bonej/plugins/PurifyTest.java
Previously it threw an exception if no particles were found.
Adds test cases for no particles, multiple particles and a single
particle in multiple locations.
=> Purify gracefully handles the situation when there are no particles

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java, Legacy/bonej/src/main/java/org/bonej/plugins/Moments.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleDisplay.java
An axis-aligned bounding box has been implemented that takes the particle's principal axes as input and outputs the centroid and side length of the aligned bounding box. Users can choose to display numerical or 3D rendered results.
Addresses #288 
See the forum post for motivation and example output.
https://forum.image.sc/t/intersection-of-longest-principal-axis-and-object-surface/49105/8
Performance enhancements by
- multithreading analysis steps
- replacing Java Maps with Eclipse Collections primitive maps
- reducing neighbourhood handling during the first pass
- multithreading bucket fountain
Gains are most obvious on larger images (several GB) containing many particles; on very small images (2 MB) performance is similar or slower. Performance is also strongly affected by JRE …
=> Calculate the aligned bounding box for each particle; performance enhancements

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java
The cost involved in running many threads does not pay off for smaller images with few particles, so this version 'changes gears' from single threaded to multithreaded once a cut point (1×10⁶) of particle first labels is reached.
This change also means that first labels are counted more efficiently and earlier, which removes the need to iterate over the `IntHashSets` in `makeLutMap()`.
=> Use multithreaded bucket fountain only when there are >1m particles

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java
Logging with LogService is intended to reduce dependence on there being a live UI, so that the wrapper can be called from a headless script more reliably.
=> Show a warning in the log rather than in a UI dialog.

Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java
#303 removed a UI warning that this test checked.
=> Remove test for GUI dialog warning behaviour that has been removed

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java
Refactors the output behaviour of the ITA plugin wrapper so that whether a skeleton image is shown is under total control of the user option. Both user option and image output are specified as Parameters conforming to the IJ2 plugin design language.
=> Intertrabecular Angles: optionally show the skeleton image using Parameter conventions

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FitEllipsoidWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java, Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/Common.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/CommonTest.java
The anisotropy check previously always showed a GUI if the image was anisotropic, but this broke headless execution. If code is called from a headless environment, e.g. a Python script, a warning is printed to the console and execution continues, even if results may be unreliable.
=> Refactor image anisotropy check to handle headless execution.

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/headless/AbstractWrapperHeadlessTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/headless/IntertrabecularAnglesWrapperHeadlessTest.java, README.md
Fixes #317 
Some other pertinent information:
- Calibration is used only to merge short branches into nodes; everywhere else pixel spacing is ignored (used neither for measurements nor reporting)
- Test base class added to help improve test coverage to handle headless operation of the Wrapper plugins, to catch bugs when called from Python or macros.
=> Improve headless calling of intertrabecular angles

Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AbstractWrapperTest.java
It appears that this `headless` setting is persistent across test classes, so classes must declare what they want (headless or not) before executing test methods.
Fixes #320
=> Set the ImageJ test instance's UI to not headless.

Legacy/util/src/main/java/org/bonej/geometry/Ellipsoid.java
Hi,
This commit just changes the visibility of the getXMinAndMax method in the Ellipsoid class to public, so it matches getYMinAndMax and getZMinAndMax and can be used elsewhere.
Cheers,
Stephen
=> Changed method visibility in Ellipsoid

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceAreaWrapperTest.java
The axis checker in Surface Area is redundant because the same functionality is provided in AxisUtils.
Fixes #324
=> Use the isotropy checker in AxisUtils for calibrating surfaces

Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceAreaWrapperTest.java
Need to remember to run `mvn test -P allTests` before merging to `master`...
This PR fixes a failing test. Maven complains:
```
[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.547 s <<< FAILURE! - in org.bonej.wrapperPlugins.SurfaceAreaWrapperTest
[ERROR] testResults(org.bonej.wrapperPlugins.SurfaceAreaWrapperTest)  Time elapsed: 0.03 s  <<< FAILURE!
java.lang.AssertionError
at org.bonej.wrapperPlugins.SurfaceAreaWrapperTest.testResults(SurfaceAreaWrapperTest.java:181)
```
=> SurfaceAreaWrapperTest: update to include the stlDirectory Parameter

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Ran into this issue working on a [new napari-imagej use case](https://github.com/imagej/napari-imagej/pull/240)
[`ThicknessWrapper`](https://github.com/bonej-org/BoneJ2/blob/2683c50e8990a6deb767f3c954445fcee52e942e/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java#L234) ensures that the input image is binary, but it makes the assumption on a threshold which may not make sense based on the input image's unique values.
This PR adjusts the threshold when running the plugin, such that the threshold is halfway between the two unique values.
=> Set thickness threshold based on input range

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Reverts bonej-org/BoneJ2#332
Thanks for the contribution @gselzer and sorry to have to revert this one.
For many years we have been communicating with BoneJ users that 0 is background ("marrow space") and 255 is foreground ("bone tissue"), so implementing a change where this ImageJ-wide convention is not strictly followed breaks this assumption. The expected user behaviour is to do the image segmentation (binarisation) first, into a [0,255] image, then run all the subsequent operations on that image. In this way consistency of the pixels used in the different analyses is maintained without having to copy over the threshold value between plugins, or to implement the same interpolation routine that you have suggested here in all the plugins. If a user's image is logically binary in some …
=> Revert "Set thickness threshold based on input range"

Legacy/bonej/src/main/java/org/bonej/plugins/Connectivity.java
Maths as written are processed as ints meaning it overflows before getting to the doubles. Casting to long at the beginning fixes it.
The result was that for images with side lengths > 1300 pixels, Conn.D would be reported as negative, which is physically impossible because it implies a negative volume that cannot exist in this universe, when Connectivity itself is positive.
=> Fix an int overflow caused by int multiplications

Modern/ops/src/main/java/org/bonej/ops/ellipsoid/EllipsoidOptimisationStrategy.java, Modern/ops/src/main/java/org/bonej/ops/ellipsoid/QuickEllipsoid.java, Modern/ops/src/test/java/org/bonej/ops/ellipsoid/QuickEllipsoidTest.java
`Arrays.sort()` carries overhead because it's generalised. But we know precisely the case here, which is always a 3-element array. Profiling shows that while assigning ellipsoid IDs most (98% !) of the time is spent in `getSortedRadii()`. This dedicated 3-way sort is about 2× faster than Arrays.sort in a basic performance test.
```
Arrays.sort took 76.890026 ms for 1000000 iterations
ThreeWay took 34.917113 ms for 1000000 iterations
```
```java
import java.util.Arrays;
import java.util.Random;
public class ThreeWaySortPerformance {
public static void main(String[] args) {
final Random rand = new Random();
final int nTrials = (int) 1E6;
final double[] radii = new double[3];
long start = System.nanoTime();
long end = System.nanoTime();
long cumulativeTime = 0;
for (int i = 0; i < nTrials; …
```
=> Use dedicated 3-way sort

Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java
Triangles in the surface mesh share vertices but the vertices are repeated for every triangle in the mesh. This change reduces the number of points for the surface by 4-6× and should in principle reduce the time for brute-force all-to-all calculations used by Feret max by 16-36×. In testing on small meshes there is a several-fold speed up but not as much as predicted.
=> Filter out redundant surface mesh vertices

Legacy/bonej/src/main/java/org/bonej/plugins/SliceGeometry.java
Seems like there has been a regression or change of behaviour in IJ, around ROIs and getting bounds.
This code change makes ROI handling more explicit and uses only ImagePlus methods (not ImageProcessor or ImageStack).
Fixes #345
=> Slice Geometry: Handle ROIs (or lack of them) more gracefully

Legacy/bonej/pom.xml, Legacy/bonej/src/main/java/org/bonej/plugins/Moments.java, Legacy/bonej/src/main/java/org/bonej/plugins/Orienteer.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java, Legacy/bonej/src/main/java/org/bonej/plugins/ParticleDisplay.java, Legacy/bonej/src/main/java/org/bonej/plugins/SliceGeometry.java, Modern/ops/pom.xml, Modern/ops/src/main/java/org/bonej/ops/ellipsoid/QuickEllipsoid.java, Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidFactorErrorTrackingTest.java, Modern/utilities/pom.xml, Modern/utilities/src/main/java/org/bonej/utilities/Visualiser.java, Modern/utilities/src/test/java/org/bonej/utilities/RoiManagerUtilTest.java, Modern/wrapperPlugins/pom.xml, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AbstractWrapperTest.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/CommonWrapperTests.java, Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java, pom.xml
This is a test to see whether the slow wrapper tests that use Mockito will complete on GitHub Actions.
Also, to see whether the tests that rely on Mockito mocking the ImageJ UI pass.
=> Update scijava, run wrapper tests by default

Modern/wrapperPlugins/pom.xml
bonej-plus release versions are now available [at maven.scijava.org](https://maven.scijava.org/#nexus-search;gav~org.bonej~bonej-plus~~~). The github packages repository is retained in case there's a need to get snapshot versions remotely, however, it might not be needed long-term if scijava works out.
=> Use bonej-plus-0.0.6

pom.xml
Send only releases and not snapshots to scijava Maven repository.
=> Don't send snapshots to scijava Maven
