bonej-org/BoneJ2

IntegrationTestLogs/Thickness.txt
Modern/utilities/src/main/java/org/bonej/utilities/RoiManagerUtil.java
Modern/utilities/src/test/java/org/bonej/utilities/RoiManagerUtilTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java

Add an option to limit the thickness maps to ROIs in the RoiManager

Thickness ROIs

---

Modern/ops/src/main/java/org/bonej/ops/connectivity/EulerCorrection.java
Modern/ops/src/test/java/org/bonej/ops/connectivity/EulerCorrectionTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java

Forgot to add support for hyperstacks to the EulerCorrection Op

Add hyperstacks to EulerCorrection

---

Modern/ops/src/main/java/org/bonej/ops/ThresholdElementFraction.java
Modern/ops/src/test/java/org/bonej/ops/ThresholdElementFractionTest.java
Modern/utilities/src/main/java/org/bonej/utilities/AxisUtils.java
Modern/utilities/src/test/java/org/bonej/utilities/AxisUtilsTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThresholdElementFractionWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/WrapperUtils.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThresholdElementFractionWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/WrapperUtilsTest.java

Add the first iteration of the BoneJ2 version of the Volume Fraction (voxel) plugin.

ThresholdElementFraction

---

IntegrationTestLogs/Connectivity.txt
Modern/ops/src/main/java/org/bonej/ops/connectivity/EulerCorrection.java
Modern/ops/src/main/java/org/bonej/ops/connectivity/Octant.java
Modern/ops/src/test/java/org/bonej/ops/connectivity/EulerCharacteristicFloatingTest.java
Modern/ops/src/test/java/org/bonej/ops/connectivity/EulerCorrectionTest.java
Modern/ops/src/test/java/org/bonej/ops/connectivity/OctantTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java

Previous pull request from branch was broken because I forgot to push

Fix broken PR

---

Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/ElementFraction.java
Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/SurfaceFraction.java
Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/SurfaceMask.java
Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/Thresholds.java
Modern/ops/src/test/java/org/bonej/ops/thresholdFraction/ElementFractionTest.java
Modern/ops/src/test/java/org/bonej/ops/thresholdFraction/SurfaceFractionTest.java
Modern/ops/src/test/java/org/bonej/ops/thresholdFraction/SurfaceMaskTest.java
Modern/utilities/src/main/java/org/bonej/utilities/ElementUtil.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java

Complete an iteration of the surface fraction tool.
Add a wrapper for the surface fraction op
Refactor the ops so that they operate on `RandomAccessibleInterval` instead of `ImgPlus`

Complete surface fraction iteration

---

Legacy/bonej/pom.xml
Legacy/pom.xml
Legacy/pqct/pom.xml
Legacy/util/pom.xml
Modern/ops/pom.xml
Modern/ops/src/main/java/org/bonej/ops/CentroidLinAlg3d.java
Modern/ops/src/main/java/org/bonej/ops/TriplePointAngles.java
Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/ElementFraction.java
Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/SurfaceFraction.java
Modern/ops/src/main/java/org/bonej/ops/thresholdFraction/SurfaceMask.java
Modern/ops/src/test/java/org/bonej/ops/CentroidLinAlg3dTest.java
Modern/ops/src/test/java/org/bonej/ops/TriplePointAnglesTest.java
Modern/ops/src/test/java/org/bonej/ops/thresholdFraction/SurfaceFractionTest.java
Modern/pom.xml
Modern/testImgs/pom.xml
Modern/testImgs/src/main/java/org/bonej/testImages/Cuboid.java
Modern/testImgs/src/main/java/org/bonej/testImages/HollowCuboid.java
Modern/testImgs/src/main/java/org/bonej/testImages/WireFrameCuboid.java
Modern/utilities/pom.xml
Modern/wrapperPlugins/pom.xml
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ConnectivityWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IsosurfaceWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SkeletoniseWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/TriplePointAnglesWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IsosurfaceWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java

Update dependencies and code to current API

Update to Modern API

---

Modern/ops/src/main/java/org/bonej/ops/RotateAboutAxis.java
Modern/ops/src/test/java/org/bonej/ops/RotateAboutAxisTest.java

The RotateAboutAxis op had too many bells and whistles and was too clunky.

Refactor rotation op

---

Modern/ops/src/main/java/org/bonej/ops/SolveQuadricEq.java
Modern/ops/src/test/java/org/bonej/ops/SolveQuadricEqTest.java

Add an op to find a best-fit solution for a quadratic surface.

Quadric eq

---

Modern/ops/src/main/java/org/bonej/ops/SolveQuadricEq.java
Modern/ops/src/main/java/org/bonej/ops/ellipsoid/Ellipsoid.java
Modern/ops/src/main/java/org/bonej/ops/ellipsoid/EllipsoidPoints.java
Modern/ops/src/main/java/org/bonej/ops/ellipsoid/QuadricToEllipsoid.java
Modern/ops/src/test/java/org/bonej/ops/SolveQuadricEqTest.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidTest.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/QuadricToEllipsoidTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/CommonWrapperTests.java

Add more properties to the Ellipsoid class, and an ellipsoid related op.

Ellipsoid ops

---

Modern/ops/src/main/java/org/bonej/ops/ellipsoid/Ellipsoid.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidTest.java

Add semi-axes setter and constructor to the Ellipsoid class. Ellipsoid can now be created from vectors from which radii and orientation is determined.

Add semi-axes setter and constructor

---

IntegrationTestLogs/FitEllipsoid.txt
Legacy/bonej/src/main/java/org/bonej/plugins/EllipsoidFitter.java
Legacy/bonej/src/main/resources/plugins.config
Modern/ops/src/main/java/org/bonej/ops/SolveQuadricEq.java
Modern/utilities/src/main/java/org/bonej/utilities/RoiManagerUtil.java
Modern/utilities/src/test/java/org/bonej/utilities/RoiManagerUtilTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FitEllipsoidWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/Common.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtils.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FitEllipsoidWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThicknessWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/CommonTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtilsTest.java

Add fit ellipsoid command. Refactor shared code into utility methods.

Fit ellipsoid command

---

Modern/ops/src/main/java/org/bonej/ops/BoxIntersect.java
Modern/ops/src/test/java/org/bonej/ops/BoxIntersectTest.java

Adds the box intersect op for finding the intersection points between a line and an interval.

Box intersect

---

Modern/ops/src/test/java/org/bonej/ops/mil/MILPOCDirectionComponents.java
Modern/ops/src/test/java/org/bonej/ops/mil/MILPOCSampling.java

Another manual proof of concept test class, that shows that a vector grid can be used to sample image uniformly from different directions. Direction components are shown in the result image on different channels: X is red, Y is green and Z is blue.

Second Mean intercept length proof of concept

---

Legacy/bonej/pom.xml
Legacy/bonej/src/main/resources/plugins.config
Legacy/pom.xml
Legacy/util/pom.xml
Legacy/util/src/main/java/org/bonej/geometry/Centroid.java
Legacy/util/src/main/java/org/bonej/geometry/Ellipsoid.java
pom.xml

* Clean Javadoc 
* Move plugins under _BoneJ Legacy_ submenu
* Releases Maven artefacts
* Include Legacy artefacts to the aggregator build.

Improve Legacy artefacts for next experimental release

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceFractionWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java

This branch was originally going to add first uses of SciView to BoneJ, but since it's going to be some time before that can be merged to `master`, I want to add these fixes and the refactoring now.

Refactor code

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java

Adds descriptions for the parameters in `AnalyseSkeletonWrapper`. These descriptions show as tooltips to the user. Fixes issue #120.

Add @Parameter descriptions

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ElementFractionWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java

* Changes wrapper so that it shows area/volume separately for each 2D/3D subspace
* Adds tests

Report element fraction for each spatial subspace

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThicknessWrapperTest.java

Also update tests to reflect single row of results
Fixes #132

Thickness: add all the results to the same row

---

Modern/ops/src/main/java/org/bonej/ops/ellipsoid/DistanceFromEllipsoidSurfaceOp.java
Modern/ops/src/main/java/org/bonej/ops/ellipsoid/Ellipsoid.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/DistanceFromEllipsoidSurfaceOpTest.java
Modern/ops/src/test/java/org/bonej/ops/mil/LinePlaneTest.java
Modern/utilities/src/main/java/org/bonej/utilities/AxisUtils.java
Modern/utilities/src/main/java/org/bonej/utilities/ElementUtil.java
Modern/utilities/src/main/java/org/bonej/utilities/ImagePlusUtil.java
Modern/utilities/src/main/java/org/bonej/utilities/RoiManagerUtil.java
Modern/utilities/src/main/java/org/bonej/utilities/SharedTable.java
Modern/utilities/src/main/java/org/bonej/utilities/Streamers.java
Modern/utilities/src/test/java/org/bonej/utilities/AxisUtilsTest.java
Modern/utilities/src/test/java/org/bonej/utilities/ElementUtilTest.java
Modern/utilities/src/test/java/org/bonej/utilities/ImagePlusUtilTest.java
Modern/utilities/src/test/java/org/bonej/utilities/RoiManagerUtilTest.java
Modern/utilities/src/test/java/org/bonej/utilities/SharedTableTest.java
Modern/utilities/src/test/java/org/bonej/utilities/StreamersTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/FractalDimensionWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/ThicknessWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/HyperstackUtils.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtils.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FractalDimensionWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/CommonTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/HyperstackUtilsTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/ResultUtilsTest.java

* Addresses inconsistent style in throwing exceptions (fixes #116)
* Adds tests to check that exceptions are thrown
* Other small fixes (see commit history)
* Updates Javadocs and signatures (`throws`)

Make exceptions consistent

---

Legacy/bonej/src/main/java/org/bonej/plugins/ReporterOptions.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/UsageReporterOptions.java

https://imagej.net/BoneJ2#Usage_reporting

Reporter: Added help links to Wiki user docs (not bonej.org):

---

Legacy/bonej/src/main/resources/plugins.config

These utility methods suit being placed with other stack utility methods rather than in a BoneJ submenu.

Move Delete Slice Range and Check Voxel Depth menu items to Image>Stacks

---

Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java

This series of commits fixes bugs and adds features to Particle Analyser and by extension Purify
- surfaces may be optionally coloured by orientation #160 
- draw best fit ellipsoids on a new stack https://forum.image.sc/t/question-about-using-development-versions/24590/2
- fixes an out-by-one bug in 26-neighbourhood scanning #167 
- fixes a background particle bug in Purify #170 
- fixes poor performance introduced by unnecessary use of Streams

Improvements to Particle Analyser

---

Modern/utilities/src/main/java/org/bonej/utilities/ElementUtil.java

Tidy up that should have been in the last PR.

Remove unused imports, use Cursor.next() not .fwd() and .get()

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java

Calculate DA using eigenvalues; display eigenvectors in the results table

---

.travis.yml
Legacy/bonej/pom.xml
Legacy/util/pom.xml
Modern/ops/pom.xml
Modern/utilities/pom.xml
Modern/wrapperPlugins/pom.xml
pom.xml

Update maven.imagej.net to maven.scijava.org

---

Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ConnectivityWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ElementFractionWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FitEllipsoidWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/FractalDimensionWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SkeletoniseWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceAreaWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/SurfaceFractionWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/ThicknessWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/CommonTest.java

Adds small fixes to the wrapper tests, most notably a randomly failing test for ConnectivityWrapper that I noticed when working on something else.

Small fixes to wrapper tests

---

Modern/utilities/src/main/java/org/bonej/utilities/ImageBoundsUtil.java
Modern/utilities/src/test/java/org/bonej/utilities/ImageBoundsUtilTest.java

simple outOfBounds utility class that avoids code duplication across BoneJ2

add outOfBounds utility

---

Legacy/bonej/src/main/java/org/bonej/plugins/Moments.java

Single-threaded methods are really slow for pixelwise operations on large images. This commit makes Moments of Inertia calculation much faster (depending on hardware resources).

Moments: multithread all the pixelwise operations

---

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleDisplay.java
Legacy/util/src/main/java/org/bonej/geometry/FitEllipsoid.java
Legacy/util/src/main/java/org/bonej/geometry/Vectors.java
Legacy/util/src/test/java/org/bonej/geometry/FitEllipsoidTest.java

- a lot of Javadoc
- exceptions and handling

Code style improvements, after comments on PR #200

---

Modern/ops/src/main/java/org/bonej/ops/mil/ParallelLineMIL.java
Modern/ops/src/main/java/org/bonej/ops/mil/PlaneParallelLineGenerator.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/DistanceFromEllipsoidSurfaceOpTest.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidPointsTest.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidTest.java
Modern/ops/src/test/java/org/bonej/ops/ellipsoid/QuadricToEllipsoidTest.java
Modern/ops/src/test/java/org/bonej/ops/mil/ParallelLineMILTest.java
Modern/ops/src/test/java/org/bonej/ops/mil/PlaneParallelLineGeneratorTest.java
Modern/utilities/src/test/java/org/bonej/utilities/AxisUtilsTest.java
Modern/utilities/src/test/java/org/bonej/utilities/ElementUtilTest.java
Modern/utilities/src/test/java/org/bonej/utilities/RoiManagerUtilTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AbstractWrapperTest.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java

* Clarifies naming (section -> segment) as discussed in email
* Line generator now validates its constructor parameters
* Removes unused 'seed' parameters
* Marks big static objects in tests for garbage collection.

Anisotropy style fixes

---

Modern/ops/src/main/java/org/bonej/ops/mil/ParallelLineMIL.java
Modern/ops/src/main/java/org/bonej/ops/mil/PlaneParallelLineGenerator.java
Modern/ops/src/test/java/org/bonej/ops/mil/PlaneParallelLineGeneratorTest.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnisotropyWrapperTest.java

* Parameter "lines per dimension" changed to "lines per direction" so that
it scales linearly.
* MIL length is now a multiple of longest image diagonal
* Fixes slight bias in sampling

Fix issue #204

---

Legacy/bonej/pom.xml
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java
Legacy/util/pom.xml

Runs Skeletonize3D and AnalyzeSkeleton on each particle individually.
This is in response to #214 and https://forum.image.sc/t/counting-number-of-pores-in-3d/34092/13

Particle Analyser: add branch length and branch count measurements

---

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java
Modern/utilities/src/main/java/org/bonej/utilities/AxisUtils.java

Fix javadoc warnings

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapperTest.java

This PR fixes issue #219, and fixes other small, mostly stylistic things in EllipsoidFactorWrapper

Address issue #219 and add little fixes

---

Legacy/bonej/pom.xml
Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java

`ConnectedComponents` leans heavily on `HashSet<Integer>` but it is bloated and slow. [Eclipse Collections](https://github.com/eclipse/eclipse-collections) has a faster primitive `IntHashSet`. This PR swaps out `HashSet<Integer>` for `IntHashSet`. Performance improvement for larger images is on the order of 20%
```
//With IntHashSet
Particle labelling finished in 56 ms
Particle labelling finished in 53 ms
Particle labelling finished in 58 ms
Particle labelling finished in 43 ms
Particle labelling finished in 51 ms
Particle labelling finished in 222 ms
Particle labelling finished in 225 ms
Particle labelling finished in 258 ms
Particle labelling finished in 198 ms
Particle labelling finished in 253 ms
Particle labelling finished in 1156 ms
Particle labelling finished in 833 ms
Particle …
```

Use Eclipse Collections' primitive HashSet IntHashSet

---

Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java

Report feret extrema points alongside feret diameter for each particle

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java

Problem was that macro recording recorded the call to Skeletonize within EF. When _seedOnTopologyPreserving = false_ recording worked fine.

Fix issue #235

---

Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleCounter.java
Legacy/bonej/src/main/java/org/bonej/plugins/ParticleDisplay.java

Also fixes an NPE introduced by last commits on this branch

Add Feret point display to 3D Viewer

---

CONTRIBUTING.md
Legacy/bonej/src/main/java/org/bonej/plugins/Connectivity.java
Legacy/bonej/src/main/java/org/bonej/plugins/Purify.java
Legacy/bonej/src/main/java/org/bonej/plugins/UsageReporter.java
Legacy/util/src/main/java/org/bonej/geometry/Ellipsoid.java
Legacy/util/src/main/java/org/bonej/geometry/FitEllipsoid.java
Legacy/util/src/main/java/org/bonej/util/Multithreader.java
Legacy/util/src/test/java/org/bonej/geometry/CentroidTest.java
Legacy/util/src/test/java/org/bonej/geometry/EllipsoidTest.java
Legacy/util/src/test/java/org/bonej/geometry/FitEllipsoidTest.java
Legacy/util/src/test/java/org/bonej/geometry/FitSphereTest.java
Legacy/util/src/test/java/org/bonej/geometry/TrigTest.java
Legacy/util/src/test/java/org/bonej/geometry/VectorsTest.java
Modern/ops/src/main/java/org/bonej/ops/ellipsoid/DistanceFromEllipsoidSurfaceOp.java
Modern/ops/src/main/java/org/bonej/ops/ellipsoid/EllipsoidOptimisationStrategy.java
Modern/ops/src/main/java/org/bonej/ops/mil/ParallelLineMIL.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapper.java
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/UsageReporter.java
pom.xml

- Change HTTP to HTTPS where possible
- remove broken links
- update dx.doi.org to doi.org

Clean up URLs

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapper.java
Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/AnalyseSkeletonWrapperTest.java

Fixes #256
Updates the test to use a calibrated input image.

Calibrate detailed skeleton branch output.

---

Legacy/bonej/src/main/java/org/bonej/plugins/ParticleAnalysis.java
Legacy/bonej/src/main/java/org/bonej/plugins/Purify.java

This is a code readability and minor performance tweak that reduces array lookups and loop complexity.

Reduce 2D array lookups in inner loops

---

Legacy/bonej/src/main/java/org/bonej/plugins/SliceGeometry.java

Quit Slice Geometry if a non-rectangular ROI is provided

---

Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java

Doube M. 2021 Multithreaded two-pass connected components labelling and
particle analysis in ImageJ. Roy. Soc. Open Sci. 8.
(doi:10.1098/rsos.201784)

Javadoc: reference the RSOS paper

---

pom.xml

Bump scijava to 31.1.0

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java

Originally requested here:
https://forum.image.sc/t/saving-anisotropy-mil-vector-in-fiji/63755

Add an option to print all the MIL vectors to a result table

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/SurfaceAreaWrapper.java

This should make it possible to use Surface Area from a headless script, by passing the output directory as an argument in the CommandService.run() method. The rest of the file name is generated automatically from the input file name + a submesh number (if needed) + .stl.
Reported here:
https://forum.image.sc/t/bonej-thickness-macro-wont-work-using-pyimagej/80704/8

Set the STL output location during setup by using @Parameter annotation.

---

Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java

Ran into this issue working on a [new napari-imagej use case](https://github.com/imagej/napari-imagej/pull/240)
`EllipsoidFactorWrapper` [expects an input image of `UnsignedIntType`](https://github.com/bonej-org/BoneJ2/blob/2683c50e8990a6deb767f3c954445fcee52e942e/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java#L151), but funnily enough it can be run with images of many types that are not of this data type. I didn't see any real need for the input image data type to be `UnsignedIntType`, so I broadened the type out to any native real type.

Broaden the data type of EllipsoidFactor input images

---

Modern/ops/src/main/java/org/bonej/ops/ellipsoid/QuickEllipsoid.java

May be useful for external clients of the API.

Mark getEllipsoidTensor() as public

---

Legacy/util/src/main/java/org/bonej/util/BoneList.java

Include a few more long-bone(ish) bones in the bone list.
Fixes #347

Expand the list of bone names for matching

---

Modern/wrapperPlugins/pom.xml
Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/GPUCheckerWrapper.java

Improve handling of first use of BoneJ+
- display Token Check dialog when running GPU Check
- use improvements in bonej-plus-0.0.5, such as refusing to run when the device to use hasn't been set.

Plus 0.0.5

---

Modern/utilities/src/test/java/org/bonej/utilities/RoiManagerUtilTest.java
Modern/wrapperPlugins/pom.xml
pom.xml

Plus 0.0.8
